### PR TITLE
Add Naturalclar to FUNDING.yml

### PR DESCRIPTION
**Pull request by imbsky**
CC: @Naturalclar

### CODE REVIEW

**Comment by imbsky** [comment]
@Naturalclar If you are okay, please approve and merge this.

**Comment by Naturalclar** [comment]
@imbsky I don't think I have merge rights for this repository 🤔

**Comment by imbsky** [comment]
Oops, that's weird, I'll merge it once.

**Comment by imbsky** [comment]
Now you have all permissions!

**Pull request merged**
