### PR TITLE
Update CODEOWNERS

### PR DESCRIPTION
**Pull request by bcdady**
Addresses issue #36 by modifying the .github/CODEOWNERS file

### CODE REVIEW

**Comment by bcdady** [comment]
Hi @smorimoto are you available to take a look at my 2 recent MRs (#37, #38), or delegate them to another maintainer?

**Comment by smorimoto** [comment]
I'm away a little now and I plan to back in a few days.
What this PR point out is correct, the solution is actually different and the infrastructure repository needs to be fixed.

**Comment by bcdady** [comment]
Ok, thanks for the update and feedback @smorimoto 
What could I do to help fix the infrastructure repo?

**Comment by smorimoto** [comment]
See https://github.com/asdf-community/infrastructure/commit/dce17ee4e34fa59f16da56317b0f319898357a8b.

**Pull request closed without merging**
